### ISSUE TITLE
Error - Thanks 

### ISSUE THREAD

**Issue by apalibook** [sreegithck/AndroidWebView_FULL#1]
Kind Attn:
I am completely newbie, learning Android Studio,
AndroidWebView_FULL is exactly I needed for my community website.

I just downloaded and compiled for .apk and getting this error. (nothing changed)

/*

..\MainActivity.kt: (27, 5): Property must be initialized or be abstract
..\MainActivity.kt: (29, 5): Property must be initialized or be abstract
..\MainActivity.kt: (34, 35): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ActionBar?
..\MainActivity.kt: (35, 24): Unresolved reference: R
..\MainActivity.kt: (36, 9): Val cannot be reassigned
..\MainActivity.kt: (36, 28): Unresolved reference: R
..\MainActivity.kt: (43, 17): 'shouldOverrideUrlLoading' hides member of supertype 'WebViewClient' and needs 'override' modifier
..\MainActivity.kt: (57, 17): 'onGeolocationPermissionsShowPrompt' hides member of supertype 'WebChromeClient' and needs 'override' modifier
..\MainActivity.kt: (60, 17): 'onPermissionRequest' hides member of supertype 'WebChromeClient' and needs 'override' modifier
..\MainActivity.kt: (80, 9): Val cannot be reassigned
..\MainActivity.kt: (80, 43): Unresolved reference: R
..\MainActivity.kt: (81, 92): This class does not have a constructor
..\MainActivity.kt: (82, 17): 'onRefresh' hides member of supertype 'OnRefreshListener' and needs 'override' modifier
..\MainActivity.kt: (99, 9): 'onBackPressed' hides member of supertype 'AppCompatActivity' and needs 'override' modifier

*/

entire error in MainActivity.kt file,   
it would be really helpful if you guide me how to fix this.

Thanks in Advance.

I am using:
Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
GC: ParNew, ConcurrentMarkSweep
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: org.jetbrains.kotlin, com.google.services.firebase

**Comment by sreegithck** [comment]
Hi apalibook,

Sorry for the same, I mistakenly updated some working project. Kindly discard that. Now I updated the proper one, Please download and check it will work fine with your environment. Let me know if you get struck again
