### ISSUE TITLE
Kindly add more details.

### ISSUE THREAD

**Issue by tradeniti** [sreegithck/AndroidWebView_FULL#1]
Dear sreegithck,
First of all thank you so much for creating and Android WebView app. With so many wonderful features. Actually I have a request to add some more details so dummies like me can also so be benefited from this web View app.

**1. Kindly share how we can import this file into the Android studio.
2. Kindly share the path and the file name where we can change the app name, at version and the logo.
3. Kindly share the path and the file and the line number where we can put our web app link (url).**

This will help us to quickly build An web View app with different features.
Thank you in advance.

**Comment by sreegithck** [comment]
Download the Files as a ZIP file.
Open it in your Android Studio, use open project.
APP name please edit AndroidManifesr.xml, activity_main.xml and Mainactivity.java etc
You can find the parth of you webapp URL in mainactivity.java

Please open the project in android studio you will be able to make it.

**Comment by sreegithck** [comment]
Hope this is done, closing the issue
