### ISSUE TITLE
Is this repository related to the SIPSNITYA project that you are working on? If yes, it needs fixing, the application crashes every now and then, also, the meeting cant be rejoined if you accidentally exit, or if the meeting ends because of the unreliable network connection. 

### ISSUE THREAD

**Issue by cognitive137** [sreegithck/AndroidWebView_FULL#2]

**Comment by sreegithck** [comment]
Thank you for the feedback, Its is not exactly the project replica. still, let us check it and improve Can you please help us with some more insights like the device details in which you experience the frequent crash. Also meeting part let us get the fix. But that is a part of SIPSNITYA web APP. this just an interface to it.
