### ISSUE TITLE
download image or video 

### ISSUE THREAD

**Issue by apalibook** [sreegithck/AndroidWebView_FULL#4]
Kind Attn: Sreegit ji
going though  MainActivity.java  it looks like we can download image or video from site..
But after compilation, when I click (for 2 sec) It little vibrate .. but noting happening.  //No context menu appears//
It is very useful if we get the option to download image or video and save it to new directory created (auto) in the name of our app.
Thanks in advance.

**Comment by sreegithck** [comment]
Yes you can download, please check also see the storage permissions
